BACKPORT: FROMGIT: ASoC: core: move definition of enum snd_soc_bias_level
To fix compilation error:

- error: field 'XXX' has incomplete type

Moves definition of enum snd_soc_bias_level from soc.h to soc-dapm.h.

Signed-off-by: Tzung-Bi Shih <tzungbi@google.com>
Link: https://lore.kernel.org/r/20200625153543.85039-2-tzungbi@google.com
Signed-off-by: Mark Brown <broonie@kernel.org>

(cherry picked from commit 10e834099d38dd2c02bf2bd5feaa3997cfcf139f
 http://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git for-next)

Conflicts:
   include/sound/soc.h
[Fix conflicts due to different context base.]

BUG=b:158799671, b:169296994
TEST=AP boot to shell

Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
Change-Id: I501d1107072f311c1b5cccd62da5b2ff0c3d92fc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2282490
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2428491
Tested-by: Yilin Yang (kerker) <kerker@chromium.org>
Commit-Queue: Yilin Yang (kerker) <kerker@chromium.org>