FROMGIT: ASoC: rt1015: add missing header inclusion
To fix compilation error:

error: implicit declaration of function 'ACPI_PTR'
[-Werror,-Wimplicit-function-declaration]
                .acpi_match_table = ACPI_PTR(rt1015_acpi_match),
		                    ^

Adds the missing header "acpi.h" inclusion and sorts in alphabetical.

Signed-off-by: Tzung-Bi Shih <tzungbi@google.com>
Link: https://lore.kernel.org/r/20200625153543.85039-4-tzungbi@google.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 72ac4a4bef48e67bb26bc5a01d68c8163def013d
 http://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git for-next)

BUG=b:158799671, b:169296994
TEST=AP boot to shell

Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
Change-Id: I66080bebba671a773976a407a3498692497672f1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2243047
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2426140
Tested-by: Yilin Yang (kerker) <kerker@chromium.org>
Commit-Queue: Yilin Yang (kerker) <kerker@chromium.org>