CHROMIUM: WAR: rpmsg: glink: Remove unused variable
drivers/rpmsg/qcom_glink_native.c:1654:16: error: unused variable 'flags'
[-Werror,-Wunused-variable]

unsigned long flags;

1 error generated.

BUG=b:138962769
TEST=COMPILE

Change-Id: Id46de154e801da715fb6fd3a76b0f0abee2075b2
Signed-off-by: Khasim Syed Mohammed <khasim.mohammed@linaro.org>
(cherry picked from commit 379f3cfd896491851e34b264ae07781e142632d7
https://git.linaro.org/people/khasim.mohammed/kernel.git/log/?h=kcrashv1/chromeos-4.14-gw)
Signed-off-by: Vijay Navnath Kamble <vkambl@codeaurora.org>