BACKPORT: drm/amdgpu/amdgpu: use "*" adjacent to data name
When declaring pointer data, the "*" symbol should be used adjacent to
the data name as per the coding standards. This resolves following
issues reported by checkpatch script:
	ERROR: "foo *   bar" should be "foo *bar"
	ERROR: "foo * bar" should be "foo *bar"
	ERROR: "foo*            bar" should be "foo *bar"
	ERROR: "(foo*)" should be "(foo *)"

Signed-off-by: Deepak R Varma <mh12gx2825@gmail.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit c4c5ae67d17976d058341b24908d5f562f3ce933)
Signed-off-by: Sean Paul <seanpaul@chromium.org>

Downstream changes:
-Context conflict with 0a667b500703d ("drm/ttm: remove bdev from
 ttm_tt")

Change-Id: Id147b560e48de63f86f3dd8f5f290c7e9a671ad2