UPSTREAM: drm/imx: dw_hdmi-imx: depend on OF to fix randconfig compile tests on x86_64
The i.MX6 HDMI driver uses of_drm_find_bridge() and thus cannot be built
with CONFIG_OF disabled:

    ld: drivers/gpu/drm/imx/dw_hdmi-imx.o: in function `dw_hdmi_imx_probe':
    dw_hdmi-imx.c:(.text+0x29f): undefined reference to `of_drm_find_bridge'

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
Fixes: c805ec7eb210 ("drm/imx: dw_hdmi-imx: move initialization into probe")
Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
(cherry picked from commit 5d91295257eae2ebc01d23e2d04b891475d1ecd2)
Signed-off-by: Sean Paul <seanpaul@chromium.org>

BUG=b:187093397
TEST=Tested with single/multiple displays, suspend/resume, hotplugs on volteer/trogdor/dedede/zork, build tested on amd64/arm64-generic

Change-Id: If17929f265c7d8f52fac4826ee55430eb8c77df9