FIXUP: CHROMIUM: extcon: Use PD-notifier
0-day reports:

   ld: drivers/extcon/extcon-tcss-cros-ec.o: in function `cros_ec_tcss_remove':
>> drivers/extcon/extcon-tcss-cros-ec.c:532: undefined reference to `cros_usbpd_unregister_notify'
   ld: drivers/extcon/extcon-tcss-cros-ec.o: in function `cros_ec_tcss_probe':
>> drivers/extcon/extcon-tcss-cros-ec.c:585: undefined reference to `cros_usbpd_register_notify'
>> ld: drivers/extcon/extcon-tcss-cros-ec.c:613: undefined reference to `cros_usbpd_unregister_notify'

The driver now depends on CROS_USBPD_NOTIFY.

BUG=b:147758849
BUG=b:147460168
TEST=Compile with CONFIG_CROS_USBPD_NOTIFY=n

Change-Id: Ib8d11afe8a087a67e45a642c68674de624a28d63
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2141867
Reviewed-by: Benson Leung <bleung@google.com>