FIXUP: CHROMIUM: cros_ec: enable tight_timestamps automatically in sensor_ring
0day reports:

ERROR: "cros_ec_check_features" [drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.ko] undefined!

cros_ec_check_features() is only available if MFD_CROS_EC_CHARDEV is enabled.
Add the missing dependency.

BUG=b:112111610, chromium:944342
TEST=tight_timestamps automatically enabled on Nocturne

Change-Id: I7de0de0b097ae78f3861498af22018f6820cd6eb
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1547909
Reviewed-by: Enrico Granata <egranata@chromium.org>