FROMGIT: drm/i915/display: fix typo when returning table
Fix table returned when port_clock > 270000:

	drivers/gpu/drm/i915/display/intel_ddi_buf_trans.c:752:47: error: variable 'adlp_dkl_phy_dp_ddi_trans_hbr2_hbr3' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]

Initial version of the patch had it in a single table, but on second
version the table got split, but we continued to reference just one of
them.

Fixes: ca962882268a ("drm/i915/adl_p: Define and use ADL-P specific DP translation tables")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>
Reviewed-by: Anusha Srivatsa <anusha.srivatsa@intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20210521005209.4058702-1-lucas.demarchi@intel.com
(cherry picked from commit 6f20785b760119dfc9e5ad569110a9b0e6b3fe35
 git://anongit.freedesktop.org/drm-intel drm-intel-next)
Signed-off-by: Sean Paul <seanpaul@chromium.org>

BUG=b:187300590,b:185193184
TEST=Tested on volteer/zork, build tested on the rest

Change-Id: I6151a45df97d7cd82a81b19a2943a4605d970a24
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2921202
Tested-by: Azhar Shaikh <azhar.shaikh@intel.com>
Reviewed-by: Alex Levin <levinale@google.com>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Commit-Queue: Alex Levin <levinale@google.com>