UPSTREAM: ASoC: Intel: sof_da7219_max98373: shrink platform_id below 20 characters
Sparse throws the following warning:

sound/soc/intel/boards/sof_da7219_max98373.c:438:25: error: too long
initializer-string for array of char(no space for nul char)

Fix by using 'mx' acronym for Maxim.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Reviewed-by: Paul Olaru <paul.olaru@oss.nxp.com>
Reviewed-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
Reviewed-by: Rander Wang <rander.wang@intel.com>
Link: https://lore.kernel.org/r/20210621194057.21711-7-pierre-louis.bossart@linux.intel.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 1cc04d195dc245457a45df60e6558b460b8e4c71)

BUG=b:188623237
TEST=ODM tests audio function on Cret

Signed-off-by: Brent Lu <brent.lu@intel.com>
Change-Id: I7cb85d614fa0f5d4f171dfe00d682c47c67a2d55
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3017346
Tested-by: Ajye Huang <ajye_huang@compal.corp-partner.google.com>
Reviewed-by: Shou-Chieh Hsu <shouchieh@chromium.org>
Commit-Queue: Shou-Chieh Hsu <shouchieh@chromium.org>