FROMGIT: mt76: fix build error implicit enumeration conversion
drivers/net/wireless/mediatek/mt76/mt7915/mcu.c:114:10: error: implicit
conversion from enumeration type 'enum mt76_cipher_type' to different
enumeration type 'enum mcu_cipher_type' [-Werror,-Wenum-conversion]
                return MT_CIPHER_NONE;
                ~~~~~~ ^~~~~~~~~~~~~~

drivers/net/wireless/mediatek/mt76/mt7921/mcu.c:114:10: error: implicit
conversion from enumeration type 'enum mt76_cipher_type' to different
enumeration type 'enum mcu_cipher_type' [-Werror,-Wenum-conversion]
                return MT_CIPHER_NONE;
                ~~~~~~ ^~~~~~~~~~~~~~

Fixes: c368362c36d3 ("mt76: fix iv and CCMP header insertion")
Signed-off-by: Sean Wang <sean.wang@mediatek.com>
Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit cc3bd9339751162d90a0be00c0a1fab5f7b668f0
 https://github.com/nbd168/wireless.git mt76)

BUG=b:178754244, b:188614537
TEST=build and boot on asurada

Signed-off-by: Sean Wang <objelf@gmail.com>
Change-Id: I718b277d1f42f982ba9d4b4a6e840ccb429856e9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3022995
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Joshua Emele <jemele@chromium.org>
Tested-by: Joshua Emele <jemele@chromium.org>
Commit-Queue: Joshua Emele <jemele@chromium.org>