CHROMIUM: MALI: Disable MALI_VALHALL_DEBUG for COMPILE_TEST
If CONFIG_MALI_VALHALL_DEBUG is enabled, the mali code tries
to export static functions. This causes a compile error in v5.15.

ERROR: modpost: "kbase_cpu_vm_close" [drivers/gpu/arm/valhall/mali_kbase] is a static EXPORT_SYMBOL
ERROR: modpost: "jd_resolve_dep" [drivers/gpu/arm/valhall/mali_kbase] is a static EXPORT_SYMBOL
ERROR: modpost: "kbase_job_irq_handler" [drivers/gpu/arm/valhall/mali_kbase] is a static EXPORT_SYMBOL

Disable it for compile tests.

Change-Id: I8cd95da67027848890f8d2cc864591d11b96ccb9
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@google.com>