FIXUP: CHROMIUM: hardlockup: detect hard lockups without NMIs using secondary cpus
0-day complains:

kernel/watchdog.c:324:13: error: no previous prototype for 'watchdog_check_hardlockup'

The symbol is only used if CONFIG_HARDLOCKUP_DETECTOR_BUDDY_CPU
is enabled, so let's declare it accordingly. Drop the weak symbol
declaration because it is not really needed and just adds an unnecessary
empty function call.

BUG=None
TEST=Build with W=1

Change-Id: Ica4d93b70408bc52a4e9b0b445cfa6038362c5e2
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3031408
Commit-Queue: Marty Faltesek <mfaltesek@google.com>
Reviewed-by: Marty Faltesek <mfaltesek@google.com>