UPSTREAM: drm/msm: fix building without debugfs
The adreno driver stopped building when CONFIG_DEBUGFS is disabled:

drivers/gpu/drm/msm/adreno/adreno_device.c: In function 'adreno_load_gpu':
drivers/gpu/drm/msm/adreno/adreno_device.c:153:16: error: 'const struct msm_gpu_funcs' has no member named 'debugfs_init'
  if (gpu->funcs->debugfs_init) {
                ^~
drivers/gpu/drm/msm/adreno/adreno_device.c:154:13: error: 'const struct msm_gpu_funcs' has no member named 'debugfs_init'
   gpu->funcs->debugfs_init(gpu, dev->primary);
             ^~

This adds an #ifdef around the code that references the hidden
pointer.

Fixes: 331dc0bc195b ("drm/msm: add a5xx specific debugfs")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Rob Clark <robdclark@gmail.com>
(cherry picked from commit 288e5c8898c488298c39ff4bbf58928d30fbf99f)
Signed-off-by: Sean Paul <seanpaul@chromium.org>
Git-commit: a811dfa7f05192052f0c85a50791b243336f32fc
Git-repo: https://gitlab.freedesktop.org/seanpaul/dpu-staging
Signed-off-by: Rajesh Yadav <ryadav@codeaurora.org>

Change-Id: Ic18d552142d0e3bb465f0ee9899844e097729d81