FIXUP: CHROMIUM: virtio-wl: Use vmalloc for larger messages in virtwl_vfd_send(). (take 2)
0-day complains:

virtio_wl.c:(.text+0x1d17): undefined reference to `find_vm_area'

Indeed, Wayland now depends on MMU support. Add the missing dependency.

BUG=b:190126742
TEST=Build with CONFIG_MMU=n

Change-Id: I17d296560fa59b15e1665820f0f30c9d5a4927fa
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3031407
Reviewed-by: Sergey Senozhatsky <senozhatsky@chromium.org>