UPSTREAM: drm/msm/dp: Fix incorrect NULL check kbot warnings in DP driver
Fix an incorrect NULL check reported by kbot in the MSM DP driver

smatch warnings:
drivers/gpu/drm/msm/dp/dp_hpd.c:37 dp_hpd_connect()
error: we previously assumed 'hpd_priv->dp_cb' could be null
(see line 37)

Reported-by: kernel test robot <lkp@intel.com>
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Abhinav Kumar <abhinavk@codeaurora.org>
Reviewed-by: Stephen Boyd <swboyd@chromium.org>
Link: https://lore.kernel.org/r/1614971839-2686-2-git-send-email-abhinavk@codeaurora.org
Signed-off-by: Rob Clark <robdclark@chromium.org>
(cherry picked from commit 7d649cfe0314aad2ba18042885ab9de2f13ad809)

BUG=b:162602229
TEST=Hang DPU on Lazor; see devcoredump

Signed-off-by: Stephen Boyd <swboyd@chromium.org>
Change-Id: I75cce8ecb5258c83e64f3408b0f8cb465a14a54c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2938212
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Rob Clark <robdclark@chromium.org>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3050398
Tested-by: Philip Chen <philipchen@chromium.org>