CHROMIUM: net/wwan: t7xx: Add dependency on 64BIT
Attempts to build 32-bit images produces a number of build errors if -Werror
is enabled, and warnings otherwise.

drivers/net/wwan/t7xx/t7xx_hif_cldma.c: In function ‘cldma_tgpd_set_data_ptr’:
drivers/net/wwan/t7xx/t7xx_hif_cldma.c:90:44: error: right shift count >= width of type

drivers/net/wwan/t7xx/t7xx_hif_cldma.c: In function ‘cldma_tgpd_set_next_ptr’:
drivers/net/wwan/t7xx/t7xx_hif_cldma.c:97:40: error: right shift count >= width of type

drivers/net/wwan/t7xx/t7xx_hif_cldma.c: In function ‘cldma_rgpd_set_data_ptr’:
drivers/net/wwan/t7xx/t7xx_hif_cldma.c:104:44: error: right shift count >= width of type

and so on. This was introduced with commit c99974ce4b7 ("CHROMIUM: net:
wwan: t7xx: Control DMA interfacing h/w").

The DMA code, and with it the entire t7xx code, strictly assumes that pointers
are 64-bit values and was likely never even build-tested on 32 bit systems.
Limit the driver to 64-bit builds to clarify that it is not expected to work
or build otherwise.

BUG=b:199583119
TEST=Build i386:allmodconfig

Change-Id: Ic21806d97df7896a6486a231b2aad30752b3476d
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3156258
Reviewed-by: Daniel Winkler <danielwinkler@google.com>