FIXUP: CHROMIUM: platform/chrome: pd_update: Use usbpd notifier
0day reports:

drivers/platform/chrome/cros_ec_pd_update.c:891:
	undefined reference to `cros_usbpd_register_notify'
drivers/platform/chrome/cros_ec_pd_update.c:904:
	undefined reference to `cros_usbpd_unregister_notify'

CROS_EC_PD_UPDATE now depends on CROS_USBPD_NOTIFY, and that dependency
needs to be be spelled out.

BUG=chromium:965213, b:150649744
TEST=Build with CROS_USBPD_NOTIFY=n

Change-Id: I83ba7914be66678e81ec39af454107aca40ef6cd
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2135375
Reviewed-by: Benson Leung <bleung@google.com>