FIXUP: FROMLIST: soc: qcom: Add SoC sleep stats driver
0-day reports:

s390-linux-ld: drivers/soc/qcom/soc_sleep_stats.o:
				in function `subsystem_sleep_stats_show':
soc_sleep_stats.c:(.text+0x15a): undefined reference to `qcom_smem_get'
s390-linux-ld: drivers/soc/qcom/soc_sleep_stats.o:
				in function `soc_sleep_stats_probe':
soc_sleep_stats.c:(.text+0x432): undefined reference to `qcom_smem_get'

qcom_smem_get() is only available if QCOM_SMEM is enabled. Add the missing
dependency.

BUG=b:120564079
TEST=Test builds

Change-Id: I1c2d7951499d1198de03faaba9ef5fb085551a7a
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2370462
Reviewed-by: Stephen Boyd <swboyd@chromium.org>