UPSTREAM: ASoC: core: move definition of enum snd_soc_bias_level
To fix compilation error:

- error: field 'XXX' has incomplete type

Moves definition of enum snd_soc_bias_level from soc.h to soc-dapm.h.

Signed-off-by: Tzung-Bi Shih <tzungbi@google.com>
Link: https://lore.kernel.org/r/20200625153543.85039-2-tzungbi@google.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 10e834099d38dd2c02bf2bd5feaa3997cfcf139f)
Signed-off-by: Chintan Patel <chintan.m.patel@intel.com>

BUG=b:162008784
TEST=Test audio on volteer.

Change-Id: Ie19c35dcb4403a3623a73efc1ce624bd1e03a7d7
Signed-off-by: Mike Mason <michael.w.mason@intel.corp-partner.google.com>