FIXUP: CHROMIUM: fs: Import esdfs code
0day reports:

fs/esdfs/esdfs.h: In function 'esdfs_put_reset_lower_paths':
include/linux/stddef.h:8:14: error: positional initialization of field in 'struct' declared with 'designated_init' attribute

Also, esdfs_d_delete() is only used locally and not declared in
a header file. Make it static.

BUG=b:63876697
TEST=compile, mount esdfs

Change-Id: I44b9b48d77f1824140d08b177fa195d45a44dc76
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1108180
Reviewed-by: Gwendal Grignou <gwendal@google.com>