FIXUP: CHROMIUM: drm/evdi: Parse usb path in evdi's add sysfs attribute
drivers/gpu/drm/evdi/evdi_drv.c: In function 'add_device_with_usb_path':
drivers/gpu/drm/evdi/evdi_drv.c:285:8: error: variable 'itf_token' set but not used

itf_token is indeed not used anywhere, so just remove the variable
and the assignment.

While at it, remove all other unnecessary variable initializations,
and mark static functions static. Also add check if usb_path is NULL
(which can happen since it was allocated with kstrdup).

Change-Id: Ibeb4930d9af5f3803b4a513fef832604b3b987b5
Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2704035
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
(cherry picked from commit 6bab3ca364b5d1fdf08a55e1014aa57a3c9efe75)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2707051
Reviewed-by: Łukasz Spintzyk <lukasz.spintzyk@synaptics.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2794693
Tested-by: Rehan Ghori <rehang@chromium.org>
Commit-Queue: Rehan Ghori <rehang@chromium.org>
Reviewed-by: Pablo Ceballos <pceballos@chromium.org>
(cherry picked from commit afd869e4b2a3e36cf5ecc2c047753c5b5c1834a6)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2835567